### ISSUE TITLE
A little difference between tf version  and your code in layer_normalization

### ISSUE THREAD

**Issue by alphadl** [leviswind/pytorch-transformer#2]
hi, thanks for your implementation~ 
When I look up your code and compare with the tf-version by Kyubyong, I fond that the implementation of layer normalization in your repository is slightly differing with Kyubyong's.

followings are you code and K's code, and he added **0.5 in the denominator:

https://github.com/leviswind/pytorch-transformer/blob/master/modules.py#L69

https://github.com/Kyubyong/transformer/blob/master/modules.py#L36

**Comment by leviswind** [comment]
The standard deviation (std) is the square root of the variance.
