### ISSUE TITLE
Problem NotImplementedError？

### ISSUE THREAD

**Issue by A6Matrix** [leviswind/pytorch-transformer#3]
When I run the train.py，report this error
![image](https://user-images.githubusercontent.com/18898570/51155981-80776900-18b4-11e9-8ca5-ef129d7808ba.png)
How to solve this problem？THKS

**Comment by leviswind** [comment]
We use pytorch with version 0.3. You can solve this problem following the link below

https://github.com/salesforce/awd-lstm-lm/issues/39#issuecomment-386827279

**Comment by liperrino** [comment]
Hello. I have the same problem but i could not resolve it. Please how exactly can we resolve it? i follow the link below but there is nothing like that in your code.

**Comment by liperrino** [comment]
Ok. I have seen it. And change it like you said

**Comment by liperrino** [comment]
Please i would like to add Beam Search on your code. Can you help me?

**Comment by liperrino** [comment]
And i also want to add Transformer with attention if possible

**Comment by A6Matrix** [comment]
> Ok. I have seen it. And change it like you said

I haven't found it yet.  Could you tell me which file I should change，THX

**Comment by A6Matrix** [comment]
> Ok. I have seen it. And change it like you said

OK，I also found it，Just revise that sentence, right？
![image](https://user-images.githubusercontent.com/18898570/51293197-b51c2980-1a48-11e9-8287-45ab058d9f9d.png)

**Comment by A6Matrix** [comment]
> Ok. I have seen it. And change it like you said
F.embedding(....)，what should I replace ’F‘ with？
